# stellar.toml for the Homeless token (Homeless Coin / HCC)
VERSION = "2.0.0"

NETWORK_PASSPHRASE = "Public Global Stellar Network ; September 2015"
SIGNING_KEY = "GDKSAFCZI3U4SIZAFGY2QWTOC7DFZJGDGSBC6VLSPFYLOII24W6KFUNS"
HORIZON_URL = "https://horizon.stellar.org"

# List related accounts (issuer, distribution)
ACCOUNTS = [
  "GDKSAFCZI3U4SIZAFGY2QWTOC7DFZJGDGSBC6VLSPFYLOII24W6KFUNS",
  "GBQB7S3MUAAMWXXTJVN44XIG3CJHTTBM7UH6IKPVPG5OH2NUOJJ3P4RU"
]

[DOCUMENTATION]
ORG_NAME = "Homeless"
ORG_DBA = "Homeless Coin"
ORG_URL = "https://homeless-hcc.github.io"
ORG_LOGO = "https://homeless-hcc.github.io/assets/1homelesscoin-logo.png"
ORG_PHYSICAL_ADDRESS = "Prattville, Alabama 36066, USA"
ORG_OFFICIAL_EMAIL = "homelesscoin2025@gmail.com"
ORG_SUPPORT_EMAIL = "homelesscoin2025@gmail.com"
ORG_PHONE_NUMBER = "+12282634786"
ORG_GITHUB = "https://github.com/Homeless-HCC"
ORG_KEYBASE = ""
ORG_TWITTER = ""

ORG_DESCRIPTION = """
Supporting homeless initiatives and community outreach programs.
Homeless Coin was born from a simple, painful reality: too many people fall through the cracks, and the world moves on like nothing happened.
This coin exists to make sure those people are never ignored again. Every Homeless Coin carries the weight of someone’s cold night,
someone’s empty stomach, someone’s quiet prayer that tomorrow might hurt less than today. It carries the story of the veteran sleeping under a bridge,
the single parent holding a child close to stay warm, the teenager pretending they’re “just out walking” because admitting they have no place to go is too heavy to say out loud.
This token fights for them. Homeless Coin is a promise that someone out there still cares. It turns compassion into fuel, and fuel into real help:
blankets, shelter, food, protection, a moment of peace in a life that hasn’t had any in too long.
"""

[[PRINCIPALS]]
name = "Jason Matthew Cook"
email = "homelesscoin2025@gmail.com"
keybase = ""
github = "https://github.com/Homeless-HCC"
id_photo_hash = ""
verification_photo_hash = ""

[[CURRENCIES]]
code = "Homeless"
issuer = "GDKSAFCZI3U4SIZAFGY2QWTOC7DFZJGDGSBC6VLSPFYLOII24W6KFUNS"
is_asset_anchored = false
anchor_asset_type = "crypto"
is_unlimited = false
status = "live"
display_decimals = 7
name = "Homeless"
desc = """
Homeless Coin isn’t about crypto. It’s about humanity. Supporting homeless initiatives and community outreach programs.
We plan to allocate funds to headquarters, mobile food trucks, emergency aid, and local programs.
"""
conditions = """
There will only ever be 333000000000 Homeless Coin in existence.
HCC is not backed by a physical asset or precious metal.
Homeless value is based on the trust provided by the community that supports the cause.
"""
image = "https://homeless-hcc.github.io/assets/1homelesscoin-logo.png"
fixed_number = 333000000000
